Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

In [13]:
def vector_power(invec,N,increasing):
    if not increasing:
        op_matrix = np.array([x**(N-i-1) for x in invec for i in range(N)]).reshape(invec.size,N)
    elif increasing:
        op_matrix = np.array([x**i for x in invec for i in range(N)]).reshape(invec.size,N)
    return op_matrix
    

In [20]:
invec = np.array([3,4,5,6,7])
col_size = 3
out_mat_dec = vector_power(invec,col_size,False)
out_mat_inc = vector_power(invec,col_size,True)
print('Decreasing order of power \n\n',out_mat_dec, '\n')
print('Increasing order of power \n\n',out_mat_inc,'\n')

Decreasing order of power 

 [[ 9  3  1]
 [16  4  1]
 [25  5  1]
 [36  6  1]
 [49  7  1]] 

Increasing order of power 

 [[ 1  3  9]
 [ 1  4 16]
 [ 1  5 25]
 [ 1  6 36]
 [ 1  7 49]] 



Question: Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [33]:
import pandas as pd
import numpy as np
def findmovavg(arr):
    y = []
    k = 3
    n = len(arr)
    ws = n-k+1
    for i in range(ws):
        y.append(arr[i:i+3].mean().astype(int))
    print('Input',' '.join(arr.astype(str)),'\n')
    print('Ouput:','\n'+'-'*40)
    return pd.Series(y,index=['y'+str(i) for i in range(1,ws+1)])

In [34]:
arr = np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])

In [35]:
findmovavg(arr)

Input 3 5 7 2 8 10 11 65 72 81 99 100 150 

Ouput: 
----------------------------------------


y1       5
y2       4
y3       5
y4       6
y5       9
y6      28
y7      49
y8      72
y9      84
y10     93
y11    116
dtype: int64